### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by TOLIE-OFFICIAL** [Larry2244/OpenCore-Asrock-B560M-ITX-AC#1]
您是直接换了模块里的网卡是嘛，我自己有一块bcm94352z，应该是免驱的

结果我换掉主板内置的网卡，发现好像windows直接不识别，我的安装应该没有问题，是因为这张主板bios禁用这张网卡嘛，

如果是这样，只有换网卡了嘛，感谢！！

**Comment by Larry2244** [comment]
我使用的网卡是94360CS2，喔是Mac单系统，无法测试windows下单兼容性，但是它在我的Mac中工作良好，目前的大多数Mac免驱无线网卡在windows中都需要额外安装对应驱动，如果在Mac中工作良好的话，在windows中可以安装对应驱动试试

**Comment by TOLIE-OFFICIAL** [comment]
> 我使用的网卡是94360CS2，直接更换了板载无线网卡，我是Mac单系统，无法测试windows下单兼容性，但是它在我的Mac中工作良好，目前的大多数Mac免驱无线网卡在windows中都需要额外安装对应驱动，如果在Mac中工作良好的话，在windows中可以安装对应驱动试试

感谢回复，上午重新测试，windows下ping了一下127.0.0.1发现返回正常，故推测是驱动问题，并不是主板黑名单问题，arch和windows下都成功驱动
